### ISSUE TITLE
In Vyxal, APL, and Jelly, characters outside of the codepage will always count as 2 bytes

### ISSUE THREAD

**Issue by Steffan153** [aderepas/WeekGolf#22]
Many Unicode characters are 3 bytes.

https://github.com/aderepas/WeekGolf/blob/07766e51fcefd7e6db194e36565125de8c14a7ba/web/back/io.php#L125-L131

**Comment by aderepas** [comment]
Actually it's not really possible to know if it's encoded in 2 or 3 bytes, but maybe something like that would be better:
```php
 foreach (preg_split('//u', $code, -1, PREG_SPLIT_NO_EMPTY) as $char){ 
     if (strpos($str_vyxal, $char) !== false){ 
         $length_of_code += 1; 
     } else { 
         $bytes_count = mb_strlen($char); // Number of bytes of a string  
         $length_of_code += max(2, $bytes_count); 
     } 
 } 
```
What do you think about it ?

The idea is that: if the char isn't in the SBCS, its value cant be 1byte. And it will be counted with a UTF-8 encoding.
So it will be the maximum value between 2 and the count of bytes in UTF-8.
The max(2, ...) is important if a language has a SBCS table that doesn't include a char that is in the ASCII table.
**_For example:_**
If a language doesn't have $ in its SBCS it would be counted as 1byte without the `max(2, ...)` because its 1b with the ASCII table which wont make sens. (Hope I'm clear)


More info about `mb_strlen`: https://www.php.net/manual/fr/function.mb-strlen.php

**Comment by Steffan153** [comment]
The thing is, none of the SBCSs so far can even represent characters outside of the codepage, so if one character is outside the codepage, then the whole thing should be treated as UTF-8.

**Comment by Steffan153** [comment]
Another bug I noticed btw, `\r\n` should be replaced with `\n` even if the language uses an SBCS.

**Comment by aderepas** [comment]
Well... the problem with that is that, a language can have up to (256 + 128) chars that count has 1 byte.
If the SBCS only have chars that aren't in the ASCII table that means that there are going to be more than 256 chars encoded in 1 byte, which won't make sens. Its why I think that doing the max between 2 and the UTF-8 value is the best option

**Comment by Steffan153** [comment]
There can only be 256 chars that count as one byte. If the code uses any characters outside of that range, it can no longer use that codepage, so you would have to use UTF-8.

Here's how I would do it:

```php
$code = str_replace("\r\n", "\n", $code);
$length_of_code = 0;
$all_in_codepage = true;
foreach (preg_split('//u', $code, -1, PREG_SPLIT_NO_EMPTY) as $char){ 
   $length_of_code++;
   if (strpos($str_vyxal, $char) !== false){ 
       $all_in_codepage = false;
       break;
   }
}
if (!$all_in_codepage) {
   $length_of_code = mb_strlen($code, '8bit');
}
```

**Comment by Steffan153** [comment]
If we don't do this, then we might be able to abuse it - everything in UTF-8 is however long it is, except we get an extra amount of characters that only count as 1 byte! This would mean in Vyxal for example, there would be 257 characters representable in one byte - the Vyxal codepage plus tab.

**Comment by aderepas** [comment]
> If we don't do this, then we might be able to abuse it - everything in UTF-8 is however long it is, except we get an extra amount of characters that only count as 1 byte! This would mean in Vyxal for example, there would be 257 characters representable in one byte - the Vyxal codepage plus tab.
Why ? 
If there is a `\t` it will count has 1b, but max(2, 1) is 2. So it will be count as 2b. And every chars encoded as 3b in UTF8, will count has 3.
Well basically my idea was:
- Everything in the SBCS: 1byte
- Everything that is 1 byte or 2 in UTF-8: 2bytes
- Everything that is 3 bytes in UTF-8: 3bytes

**Comment by Steffan153** [comment]
True, but it still doesn't seem to make a proper byte count, because there's no way to represent it so that it would really be that byte count.

**Comment by aderepas** [comment]
Yes, you're right, there are going to be between 0 and 128 chars (depend on the SBCS) counted as 2bytes instead of 3bytes among the 2048 characters encoded on 2bytes. But that's not going to matter much, is it?

**Comment by Steffan153** [comment]
Probably not, I just think it would make more sense to count the whole thing as UTF-8, since that's how it's normally done.
