### ISSUE TITLE
Python character read incorrect in translate

### ISSUE THREAD

**Issue by Git-Harshit** [aderepas/WeekGolf#31]
In the [WeekGolf translate page](https://www.weekgolf.net/translate), under the table that compares several languages on the availability of several features supported/unsupported, I see that Python has a red box (indicating _false_) for reading a single character from STDIN, next to reading all of STDIN given by `open(0).read()` in the row for Python.
![image](https://github.com/aderepas/WeekGolf/assets/57865187/8b4c76f0-461b-43b4-b139-ad7b460a4c34)

However, as open(0).read() is considered for reading all of STDIN, then I would state that reading a single character from STDIN is possible in Python as well by just passing '1' as an argument to the same `.read()` method as shown in the column before it. It can be corrected here in [Client/src/data/translation.json](https://github.com/aderepas/WeekGolf/blob/main/Client/src/data/translation.json#L456)  source. A few ways in which this can be shown is: 
1. `sys.stdin.read(1)`
2. `open(sys.stdin.fileno()).read(1)` 
3. `open(0).read(1)`

The third one makes more sense to get fit in that table as it is purely a one-liner and would not need any dependencies to be imported separately for it to work (as `import sys` would be additionally needed in case of first 2 options)

Please see if this needs correction there. 

Side Note: @aderepas You have defeated me in Code Golf on my [last clash](https://www.codingame.com/clashofcode/clash/report/31711076f99f263709a2d847aca0b4b9495e3ac) at Clash of Code, which got my attention on your CoC profile which pointed to your WeekGolf site in description, checking which lead me to file this issue here. 😃

**Comment by aderepas** [comment]
Thanks for your report!

1. This one actually work and I'm going to add it!
2 & 3. Both of theses don't really work.
Yes, they read a char, but only once.
It's like `*l=open(0)` to take all the STDIN. It works once, but not twice.
The same applies for `open(0).read(1)` or `open(sys.stdin.fileno()).read(1)`.
In most cases, `input()[0]` is just shorter to take the first char of the stdin!

For example:
```py
while 1:
    print(open(0).read(1))
```
While just print the first char of the STDIN (even if the stdin is longer) and after, will error with:

```
Traceback (most recent call last):
  File "/tmp/in/prog.py", line 3, in <module>
    print(open(0).read(1))
          ^^^^^^^
OSError: [Errno 9] Bad file descriptor
```

So I don't think that adding `open(0).read(1)` is a good idea. Tho, sys.stdin.read(1), why not.


And concerning the Clash of Code, I was golfing in Ruby, so I had a big advantage x)
And someone in WeekGolf could probably beat
```rb
n,*l=*$<;l.map{|e|p e.split.sum{s=_1.to_i;s%n.to_i<1?s: 0}}
```
Tho, your code was good!
Doesn't seem easy to optimize. The only obvious thing was to put ==0 in <1 put apart from that, seems somewhat optimal for python :)

**Comment by Git-Harshit** [comment]
Thanks for your response and considering this addition.

Yes, reusability is a good point considered for adding this info in that table. Although I just tried that on Python v3.10.7, `open(0)` didn't give me any such error when used multiple times in a for/while loop. In case `open(0)` alone continues to cause this issue, `open(0).close()` before re-`open(0)` is attemptable.

😂 For CoC, Ruby has undoubtedly several shorthand advantages in Code Golfing and as a non-Rubyist I am missing out on those. Thanks for checking my submission and that `<1` instead of `==0` comparison tip, it would have further improved my submission for sure, every character gets counted there, before the timing tie-breaker.

I will refer this [WeekGolf translate](https://www.weekgolf.net/translate) table again, please close this issue once the content is added in and is live.

**Comment by aderepas** [comment]
```Dockerfile
FROM python:3.10.7

# Put the STDIN in a file
RUN echo "This is STDIN" > stdin.txt

# Put the program in main.py
RUN echo "open(0).read(1);open(0).read(1)" > main.py

# Execute it
RUN python3 main.py < stdin.txt
```
Make the following error:

```
Traceback (most recent call last):
  File "//main.py", line 1, in <module>
    open(0).read(1);open(0).read(1)
OSError: [Errno 9] Bad file descriptor
```

So I think that I'm just going to put `sys.stdin.read(1)`!
Thank you for your contribution!

**Comment by aderepas** [comment]
Fixed
